ransac_node:
  ros__parameters:
    # 话题配置
    subscribe_topic: "/io/raw_pointcloud"
    publish_ground_topic: "/gs/ground_pointcloud"
    publish_non_ground_topic: "/gs/non_ground_pointcloud"

    # RANSAC 算法参数
    distance_threshold: 13.0
    ransac_n: 3
    num_iterations: 100

gmz_node:
  ros__parameters:
    # 话题配置
    subscribe_topic: "/io/raw_pointcloud"
    publish_ground_topic: "/gs/ground_pointcloud"
    publish_non_ground_topic: "/gs/non_ground_pointcloud"

    # GMZ 算法参数
    grid_size: 20.0
    height_threshold: 0.8
    # 保存点云功能
    data_saved_dir: "/home/cx/Documents/codes/pointcloud_607_roscpp/dataset/result/Wild/01/ground_points/"
    enable_sparse_ground_points_saving: false
    enable_ground_points_saving: false
    enable_non_ground_points_saving: false